ORIENTATION_PORTRAIT = 0
ORIENTATION_PORTRAIT_UPSIDE_DOWN = 1
ORIENTATION_LANDSCAPE_LEFT = 2
ORIENTATION_LANDSCAPE_RIGHT = 3

PROJECTION_2D = 0
PROJECTION_3D = 1

CC_FIX_ARTIFACTS_BY_STRECHING_TEXEL = false
CC_FONT_LABEL_SUPPORT = 1
CC_DIRECTOR_FAST_FPS =1
CC_DIRECTOR_FPS_INTERVAL = 0.5
CC_DIRECTOR_DISPATCH_FAST_EVENTS = false
CC_DIRECTOR_MAC_USE_DISPLAY_LINK_THREAD = 1
CC_COCOSNODE_RENDER_SUBPIXEL = 1
CC_SPRITEBATCHNODE_RENDER_SUBPIXEL = 1
CC_USES_VBO = false
CC_NODE_TRANSFORM_USING_AFFINE_MATRIX = 1
CC_OPTIMIZE_BLEND_FUNC_FOR_PREMULTIPLIED_ALPHA = 1
CC_TEXTURE_ATLAS_USE_TRIANGLE_STRIP = false
CC_TEXTURE_NPOT_SUPPORT = false
CC_USE_LA88_LABELS_ON_NEON_ARCH = false
CC_SPRITE_DEBUG_DRAW = false
CC_SPRITEBATCHNODE_DEBUG_DRAW = false
CC_LABELBMFONT_DEBUG_DRAW = false
CC_LABELATLAS_DEBUG_DRAW = false

// CC_SPRITE_DEBUG_DRAW = true